[package]
name = "json-with-position"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
indexmap.workspace = true

[dev-dependencies]
expect-test.workspace = true
indoc.workspace = true
